# skaffold version >= v1.31.0
apiVersion: skaffold/v2beta22
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "v1.0.0"
  artifacts:
    - image: registry.cn-hangzhou.aliyuncs.com/ecp_builder/openyurt-operator
      custom:
        buildCommand: "make docker-build-operator"
    - image: registry.cn-hangzhou.aliyuncs.com/ecp_builder/openyurt-agent
      custom:
        buildCommand: "make docker-build-agent"

deploy:
  kustomize:
    hooks:
      before:
        - host:
            command: ["sh", "-c", "make manifests"]
    paths: ["config/default"]
