- op: add
  path: /rules/0
  value:
    apiGroups:
    - ""
    resources:
    - serviceaccounts
    - configmaps
    - services
    - pods
    - pods/status
    - pods/eviction
    - nodes
    - nodes/status
    - endpoints
    - persistentvolumeclaims
    - persistentvolumeclaims/status
    - persistentvolumes
    - secrets
    - serviceaccounts/token
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
- op: add
  path: /rules/0
  value:
    apiGroups:
    - rbac.authorization.k8s.io
    resources:
    - roles
    - rolebindings
    - clusterroles
    - clusterrolebindings
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
- op: add
  path: /rules/0
  value:
    apiGroups:
    - ""
    - apps
    resources:
    - daemonsets
    - deployments
    - statefulsets
    - controllerrevisions
    - deployments/status
    - statefulsets/status
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
- op: add
  path: /rules/0
  value:
    apiGroups:
    - ""
    - events.k8s.io
    resources:
    - events
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
- op: add
  path: /rules/0
  value:
    apiGroups:
    - coordination.k8s.io
    resources:
    - leases
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
- op: add
  path: /rules/0
  value:
    apiGroups:
    - certificates.k8s.io
    resources:
    - certificatesigningrequests
    - certificatesigningrequests/approval
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
- op: add
  path: /rules/0
  value:
    apiGroups:
    - certificates.k8s.io
    resources:
    - signers
    resourceNames:
    - "kubernetes.io/legacy-unknown"
    verbs:
    - approve
- op: add
  path: /rules/0
  value:
    apiGroups:
    - admissionregistration.k8s.io
    resources:
    - mutatingwebhookconfigurations
    - validatingwebhookconfigurations
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
- op: add
  path: /rules/0
  value:
    apiGroups:
    - apps.openyurt.io
    resources:
    - nodepools
    - uniteddeployments
    - nodepools/status
    - uniteddeployments/status
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
- op: add
  path: /rules/0
  value:
    apiGroups:
    - apiextensions.k8s.io
    resources:
    - customresourcedefinitions
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
- op: add
  path: /rules/0
  value:
    apiGroups:
    - authorization.k8s.io
    resources:
    - localsubjectaccessreviews
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
- op: add
  path: /rules/0
  value:
    apiGroups:
    - node.k8s.io
    resources:
    - runtimeclasses
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
- op: add
  path: /rules/0
  value:
    apiGroups:
    - node.k8s.io
    resources:
    - runtimeclasses
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
- op: add
  path: /rules/0
  value:
    apiGroups:
    - storage.k8s.io
    resources:
    - csidrivers
    - csinodes
    - volumeattachments
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
