# permissions for end users to view yurtclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: yurtcluster-viewer-role
rules:
- apiGroups:
  - operator.openyurt.io
  resources:
  - yurtclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.openyurt.io
  resources:
  - yurtclusters/status
  verbs:
  - get
