# permissions for end users to edit yurtclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: yurtcluster-editor-role
rules:
- apiGroups:
  - operator.openyurt.io
  resources:
  - yurtclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.openyurt.io
  resources:
  - yurtclusters/status
  verbs:
  - get
