# Default values for openyurt-operator chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

operator:
  image: registry.cn-hangzhou.aliyuncs.com/ecp_builder/openyurt-operator:v1.0.0
  imagePullPolicy: Always

agent:
  image: registry.cn-hangzhou.aliyuncs.com/ecp_builder/openyurt-agent:v1.0.0
  imagePullPolicy: Always

node:
  image: registry.cn-hangzhou.aliyuncs.com/ecp_builder/openyurt-node:v1.0.0
  imagePullPolicy: Always
  healthCheckTimeout: "5m"
