// +build !ignore_autogenerated

/*
Copyright 2021 The OpenYurt Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeConvertCondition) DeepCopyInto(out *NodeConvertCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	in.AckLastUpdateTime.DeepCopyInto(&out.AckLastUpdateTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeConvertCondition.
func (in *NodeConvertCondition) DeepCopy() *NodeConvertCondition {
	if in == nil {
		return nil
	}
	out := new(NodeConvertCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeLocalDNSCache) DeepCopyInto(out *NodeLocalDNSCache) {
	*out = *in
	if in.Enable != nil {
		in, out := &in.Enable, &out.Enable
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeLocalDNSCache.
func (in *NodeLocalDNSCache) DeepCopy() *NodeLocalDNSCache {
	if in == nil {
		return nil
	}
	out := new(NodeLocalDNSCache)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *YurtAppManager) DeepCopyInto(out *YurtAppManager) {
	*out = *in
	if in.InstallCRD != nil {
		in, out := &in.InstallCRD, &out.InstallCRD
		*out = new(bool)
		**out = **in
	}
	if in.EnableController != nil {
		in, out := &in.EnableController, &out.EnableController
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new YurtAppManager.
func (in *YurtAppManager) DeepCopy() *YurtAppManager {
	if in == nil {
		return nil
	}
	out := new(YurtAppManager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *YurtCluster) DeepCopyInto(out *YurtCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new YurtCluster.
func (in *YurtCluster) DeepCopy() *YurtCluster {
	if in == nil {
		return nil
	}
	out := new(YurtCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *YurtCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *YurtClusterList) DeepCopyInto(out *YurtClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]YurtCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new YurtClusterList.
func (in *YurtClusterList) DeepCopy() *YurtClusterList {
	if in == nil {
		return nil
	}
	out := new(YurtClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *YurtClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *YurtClusterSpec) DeepCopyInto(out *YurtClusterSpec) {
	*out = *in
	in.YurtHub.DeepCopyInto(&out.YurtHub)
	in.YurtTunnel.DeepCopyInto(&out.YurtTunnel)
	in.YurtAppManager.DeepCopyInto(&out.YurtAppManager)
	in.NodeLocalDNSCache.DeepCopyInto(&out.NodeLocalDNSCache)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new YurtClusterSpec.
func (in *YurtClusterSpec) DeepCopy() *YurtClusterSpec {
	if in == nil {
		return nil
	}
	out := new(YurtClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *YurtClusterStatus) DeepCopyInto(out *YurtClusterStatus) {
	*out = *in
	if in.NodeConvertConditions != nil {
		in, out := &in.NodeConvertConditions, &out.NodeConvertConditions
		*out = make(map[string]NodeConvertCondition, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	in.LastUpdateTime.DeepCopyInto(&out.LastUpdateTime)
	in.LastUpdateSpec.DeepCopyInto(&out.LastUpdateSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new YurtClusterStatus.
func (in *YurtClusterStatus) DeepCopy() *YurtClusterStatus {
	if in == nil {
		return nil
	}
	out := new(YurtClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *YurtHub) DeepCopyInto(out *YurtHub) {
	*out = *in
	if in.AccessServerThroughHub != nil {
		in, out := &in.AccessServerThroughHub, &out.AccessServerThroughHub
		*out = new(bool)
		**out = **in
	}
	if in.AutoRestartNodePod != nil {
		in, out := &in.AutoRestartNodePod, &out.AutoRestartNodePod
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new YurtHub.
func (in *YurtHub) DeepCopy() *YurtHub {
	if in == nil {
		return nil
	}
	out := new(YurtHub)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *YurtTunnel) DeepCopyInto(out *YurtTunnel) {
	*out = *in
	if in.Enable != nil {
		in, out := &in.Enable, &out.Enable
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new YurtTunnel.
func (in *YurtTunnel) DeepCopy() *YurtTunnel {
	if in == nil {
		return nil
	}
	out := new(YurtTunnel)
	in.DeepCopyInto(out)
	return out
}
